tools:
  - class_name: "verl.tools.grep_search_tool.GrepSearchTool"
    config:
      type: native
      search_root: "."
      max_lines: 50
    tool_schema:
      type: function
      function:
        name: grep_search
        description: Searches the codebase for relevant information based on the given query.
        parameters:
          type: object
          properties:
            query:
              type: string
              description: A fully-formed semantic query. The tool will return search results for the query.
          required: 
            - query